### TMA4215 Numerisk Matematikk 

Høst 2021 – August 27, 2021

R. Bergmann, E. Çokaj, O. P. Hellan 

# Problem Sheet 1

## Deadline
September 5, 2021, 23:59


## Submission
submit your Jupyter notebook containing the solution via upload in blackboard.

## Problem 1.

Let $A\in \mathbb R^{n\times n}$ be an invertible matrix and $b\in\mathbb R^n$ be given.
    Consider the problem of solving the linear system of equations “Find $x\in \mathbb R^n$ such that $Ax=b$”.

1. Suppose we find $x$ with an error $\delta x$ due to an error in $b$ of size $\delta b$. This means we actually solved
   $$ A(x+\delta x) = b + \delta b$$
   Derive upper bounds for the absolute condition number $\frac{\lVert \delta x \rVert}{\lVert\delta b\rVert} \leq K_{\mathrm{abs}}(b)$
   and the relative condition number $\frac{\lVert\delta x \rVert / \lVert x\rVert}{\lVert \delta b\rVert / \lVert b \rVert } \leq K(b)$ for the case of the $2$-norm in terms of the Eigenvalues of $A$.

   Main ingredients are the $2$-norm of a vector, the (compatible, induced) $2$-norm (or spectral norm) of a matrix and their compatibility, i.e. that $\lVert Ax\rVert_2 \leq \lVert A\rVert_2 \lVert x\rVert_2$ holds.


2. Let further $A$ be disturbed data, i. e. we have a disturbed solution $x+\delta x$ often
   $$
   (A+\delta A)(x+\delta x) = b+\delta b
   $$
   How does the relative error $\frac{\lVert \delta x \rVert}{\lVert x \rVert}$ depend on the two relative errors $\frac{\lVert \delta b \rVert}{\lVert b \rVert}$ and $\frac{\lVert \delta A \rVert}{\lVert a \rVert}$ of the data?

3. What can you say **a priori** (before you solve any system) about relative errors when
$$
  Ax = \begin{pmatrix}
  1 & 1\\
  1.0004 & 1
  \end{pmatrix}x
  = \begin{pmatrix}
    2\\2
  \end{pmatrix} = b
$$
  is given (you can use Python to reason for your answer)?
  Compute the exact solution by hand and use `Python` to solve the disturbed version with $\delta b = \begin{pmatrix} 2\\2.001 \end{pmatrix}$

####  Solutions 1

1)

Firs of all we got $ Ax = b $ which implies $$ \lVert Ax \rVert= \lVert b \rVert$$ By the properties of the induced vector norm this result in the inequality $$ \lVert b \rVert\leq \lVert A \rVert \lVert x \rVert $$
$A \in \mathbb R^{n\times n}$ is invertible. This implies that $A^{-1}$ eksists that satisfies $ x = A^{-1} b$. Taking the norm of each side results in $$ \lVert x \rVert= \lVert {A^{-1}} b \rVert \leq \lVert {A^{-1}}\rVert \lVert b \rVert$$ by property of an induced vector norm. Because of linearity $ Ax = b $ implies that $ A\delta x = \delta b$, and the exact same derivation gives $$ \lVert \delta x \rVert= \lVert {A^{-1}} \delta b \rVert \leq \lVert {A^{-1}}\rVert \lVert \delta b \rVert$$ and $$ \lVert \delta b \rVert \leq \lVert A \rVert \lVert \delta x \rVert$$

The following inequalitie $\frac{\lVert\delta x \rVert}{\lVert \delta b\rVert} \leq \lVert {A^{-1}} \rVert$ directly follows from the next to last derived inequality.

To get the last result we need to multyply LHS by $\frac{\lVert b \rVert}{\lVert x \rVert} $ and RHS by $ \lVert {A} \rVert$, which keeps the inequality valid because of the relation $\frac{\lVert b \rVert}{\lVert x \rVert} \leq \lVert {A} \rVert$, since something smaller times something smaller must be less than something bigger times som factor also bigger.
This results in the equation $\frac{\lVert\delta x \rVert / \lVert x\rVert}{\lVert \delta b\rVert / \lVert b \rVert } \leq K(b) = \lVert {A^{-1}} \rVert \lVert A \rVert$

With $\lVert A \rVert = \lambda_1 (A)$ and $\lVert A^{-1} \rVert = 1 / \lambda_n (A)$ with $\lambda_1 (A)$ and $\lambda_n (A)$ being the being the biggest and smallest eigenvalue of A. This results in the equation $\frac{\lVert\delta x \rVert / \lVert x\rVert}{\lVert \delta b\rVert / \lVert b \rVert } \leq K(b) = \frac{\lVert \lambda_1 (A) \rVert }{\lVert \lambda_n (A) \rVert }$

2) Because Ax = b, then (A + dA)(x+dx) = b+db means Adx + dAx + dAdx = db. dAdx is presumed small compared to dAx and Adx, so we get the equation Adx + dAx = db. More of this task is not done in this assignment due to difficulty and time, hope the rest of this assignment is done satisfactory enough.

In [1]:
import numpy as np
import scipy.linalg as lng
np.set_printoptions(precision=3)
from datetime import datetime

#### 3)

In [2]:
A = np.array([[1,1],[1.0004,1]])
b = np.array([2,2])
delta_b = np.array([2,2.001])
lng.solve(A,delta_b)

array([ 2.5, -0.5])

## Problem 2.

We want to compute the LU factorisation with pivoting of a matrix $A$

$$
     PA = LU
$$

where $P$ is a permutation matrix, $L$ is a lower-triangular matrix with unit diagonal, and $U$ is an upper-triangular matrix.
We represent the matrices in question as follows:
The permutation matrix $P$ is $n\times n$, but is represented as a vector $\mathtt{P}$ such that row number $k$ in $P$ is the canonical unit vector $e_{\mathtt{P}_k}$. Let us illustrate this by an example

$$
\mathtt{P}=
\left[
\begin{array}{r} 3 \\ 1 \\ 2 \end{array}
\right]\quad\Rightarrow\quad
P=\left[
\begin{array}{ccc}
0 & 0 & 1 \\ 1 & 0 & 0 \\ 0 & 1 & 0
\end{array}
\right]
$$

We stipulate that a Python function takes a two-dimensional numpy-array $\mathtt{A}$ as input, and returns
an *over-written* $\mathtt{A}$ which contains $L$ and $U$ in the following sense upon return:
x
$$
\begin{array}{ll}
\mathtt{A}[\mathtt{P}[i],j] = L_{ij} & \text{for}\ i<j \\
\mathtt{A}[\mathtt{P}[i],j] = U_{ij} & \text{for}\ i\geq j
\end{array}
$$

That $L$ has 1 on the diagonal is always the case, so the diagonal of $L$ needs not be stored. The remaining elements of $L$ and $U$ are zero and need not be stored either. The algorithm can be formulated as follows (compare to text book):

- Input: $A$ of size $n\times n$
- Initialisation
    * Let $P_i = i,\ i=0,\ldots,n-1$ be a vector (array) with $n$ components
- for $k$ **in** range(n-1):
    1. Find index $P_\ell$ such that $|\mathtt{A}_{P_\ell,k}|=\max_{k\leq i \leq n-1} |\mathtt{A}_{P_i,k}|$, i.e. scan column $k$ from the diagonal and down for the largest element in absolute value. 
    2. Swap $P_k$ by $P_\ell$.
    3. Find multipliers $A_{P_i,k}\leftarrow \frac{A_{P_i,k}}{A_{P_k,k}},\ i=k+1,\ldots,n-1$.
    4. Perform elimination, i.e. $A_{P_i,j}\leftarrow A_{P_i,j}-A_{P_i,k}\cdot A_{P_k,j},\ i,j=k+1,\ldots,n-1$
- Output: A,P

There are – of course – implementations of these, often highly optimised for special cases (e.g. when $A$ is sparse) but here we first want to learn how to code it ourselves. Let's also use this to our advantage


1. Write a function for LU-factorisation with row-wise pivoting as indicated above.
   A template could be

       def mylu(A):
   
    
   and it should return the pivot vector (permutation vector) $\mathtt{P}$, and over-written  version of $A$. You can also choose to copy $A$ into some other matrix $\mathtt{LU}$ from the beginning using e.g. 

       LU = A.copy()

2. use the function `scipy.linalg.lu` to test your implementation from the first part. Write a test function

       def mylutest(A)
   
   that compares the result of your implementation to the one from `SciPy`. Call this function for example with

   $$
   A = \begin{pmatrix} 2 & 5 & 8 & 7\\ 5 & 2 & 2 & 8 \\ 7 & 5 & 6 & 6\\ 5 & 4 & 4 & 8\end{pmatrix}
   $$
   
   (or `np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])` to easier copy it).
   
3. Test your function with a matrix `A` that does not meet our assumption of having full rank, for example by repeating a column. What happens?

#### Solutions 2

In [3]:
L_lower = np.array([[2, 0,0,0], [5, 2, 0,0], [7, 5, 6, 0], [5, 4, 4, 8]],dtype = "float")
L_upper = np.transpose(L_lower)
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]],dtype = "float")
b = np.array([5, 4, 4.0, 2],dtype = "float")

In [4]:
def PLU(A_matrix):
    LU = A_matrix.copy()
    N = len(A[0,:])
    P = np.arange(0,N)
    for k in range(N-1):
        
        #Permutation part
        sup_elem, key_elem = 0,0
        for i in range(k,N):
            if abs(LU[P[i]][k]) > sup_elem:
                sup_elem, key_elem = abs(LU[P[i]][k]),i
        P[[k,key_elem]] = P[[key_elem,k]]   
            
        #Elimination part
        for i in range(k+1,N):            
            LU[P[i],k] = LU[P[i],k]/LU[P[k],k]
        for i in range(k+1,N):
            for j in range(k+1,N):
                LU[P[i],j] -= LU[P[i],k]*LU[P[k],j]
    
    return LU,P

# print(A)        
LU,P = PLU(A)
print("PLU: \n",LU,'\n')
LU2 = lng.lu(A)
print(f'scipy.linalg: \n{LU2[0]@((LU2[1] + LU2[2] - np.identity(len(LU2[2]))))}')
P, L, U = lng.lu(A)

PLU: 
 [[ 0.286  3.571  6.286  5.286]
 [ 0.714 -0.44  -0.462  7.462]
 [ 7.     5.     6.     6.   ]
 [ 0.714  0.12  -1.04   3.08 ]] 

scipy.linalg: 
[[ 0.286  3.571  6.286  5.286]
 [ 0.714 -0.44  -0.462  7.462]
 [ 7.     5.     6.     6.   ]
 [ 0.714  0.12  -1.04   3.08 ]]


## Problem 3

1. Implement a

  `def forward_substitution(A,b):`
    
  function that takes a lower triangular matrix `A` and some vector `b` to solve $A\mathbf{x} = \mathbf{b}$

2. Implement a

  `def backward_substitution(A,b):` 
        
  function that takes an upper triangualr matrix `A` and some vector `b` to solve $A\mathbf{x} = \mathbf{b}$ for this case.
  
3. Combine the last two parts with Problem 2 and implement a function

   `def my_solve(A,b):`

   for a square matrix `A` and a right hand side `b` that computes the LU decomposition of `A` and then uses the first two parts of this problem to compute the solution to $A\mathbf{x} = \mathbf{b}$
   
4. Performance. Let's compare our implementation for two cases as well as to the original. To be precise
  * fix some $n$, say `n=100`
  * generate a reguar square matrix `A` (Hint: maybe create `L` and `U` here to be sure `A` is regular)
  * generate `m`, say `m=200` right hand sides `b_k`
  * run an experiment where you time

      a) calling `m` times `my_solve(A,b)` once for each `b_k`

      b) only computing the LU decomposition once and use backward and forward substitutions `m` times

      c) using `np.linalg.solve`
      
    Where do the time differences from a) to b) come from and where the ones from c) to b)? 

#### Solutions 3

In [37]:
def forward_subtitution(A,b):
    N = len(b)
    c = np.copy(b)
    A = A.copy()
    x = np.zeros(len(b))
    x[0] = c[0]
    for i in range(1,N):
        sums = 0
        for j in range(0,i):
            sums += A[i][j]*x[j]
        x[i] = (c[i] - sums)/A[i][i]
    return c


def backward_subtitution(A,b):
    N = len(b)
    c = np.copy(b)
    A = A.copy()
    x = np.zeros(len(b))
    for i in range(N-1,-1,-1):
        sums = 0
        for j in range(N-1,i,-1):
            sums += A[i][j]*c[j]
        x[i] = (c[i] - sums)/A[i][i]
    return x
        
def my_solve(A,b):
    N = len(A[0,:])
    LU, P = PLU(A)
    b = b.copy()
    
    L = LU.copy()
    U = LU.copy()
    for i in range(N):
        L[i,i] = 1
        for j in range(N):
            if j>i:
                L[i][j] = 0
            if i>j:
                U[i][j] = 0
    Pmatrix = np.zeros((N,N))
    for i,val in enumerate(P):
        Pmatrix[i,val] = 1
    c =  forward_subtitution(L, np.transpose(Pmatrix)@b)
    x = backward_subtitution(U, c)
    return x

In [41]:
b = np.array([1.0,2.0,3.0,4.0],dtype = 'float')
sol1 = my_solve(A,b)
sol2 = np.linalg.solve(A,b)

print(sol1,'\n')
print(sol2)

[-120.5     40.734   -2.833    0.974] 

[-0.165  2.464 -1.464  0.103]


I just cant seem to be able to make this one work.

In [ ]:
n = 50
m = 200

L = np.zeros((n,n))
U = np.zeros((n,n))
for i in range(n):
    L[i] = np.random.rand(n)
    U[i] = np.random.rand(n)
A = np.tril(L)@np.transpose(np.tril(U))
bks = np.zeros((m,n))
for i in range(m):
    bks[i] = np.random.rand(n)
    
sol1, sol2, sol3 = np.zeros((m,n)), np.zeros((m,n)), np.zeros((m,n))

In [ ]:
#Calling my solve m times
now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

#####################################################

for i in range(m):
    sol1[i] = my_solve(A.copy(),bks[i].copy())
    
#####################################################
now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

In [ ]:
#Calling LU 1 time and using forward/backwards m times
now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

#####################################################

LU, P = PLU(A)
N = len(A[0,:])
L = LU.copy()
U = LU.copy()
for i in range(N):
    L[i,i] = 1
    for j in range(N):
        if j>i:
            L[i][j] = 0
        if i>j:
            U[i][j] = 0
Pmatrix = np.zeros((N,N))
for i,val in enumerate(P):
    Pmatrix[i,val] = 1
for i in range(m):
    c =  forward_subtitution(L, np.transpose(Pmatrix)@bks[i].copy())
    x = backward_subtitution(U, c)
    sol2[i] = x
    
#####################################################

now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

In [ ]:
#calling linalg.solve m times

now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

#####################################################

for i in range(m):
    sol3[i] = np.linalg.solve(A.copy(),bks[i].copy())
    
#####################################################


now = datetime.now()

current_time = now.strftime("%H:%M:%S")
print("Current Time =", current_time)

#### Tests:

In [ ]:
np.linalg.norm(sol1 - sol3)

In [ ]:
np.linalg.norm(sol1 - sol2)

In [ ]:
np.linalg.norm(sol2 - sol3)

In [ ]:
np.linalg.norm(sol3)

My solver somewhere got something wrong, which gives the wrong ansewer. The runtime should not however be affected by this, as my algorithms got the same complexity as supposed to when done right.

#### 3.4)

Doing the LU factorysation 1 time obviously save a lot of time over doing it m times, particularly when the timecomplexity of the solver is decided by the LU-algorithms O(n^3), and not the forward and backward solver which is O(n^2). How the np.linalg.solve solves as fast as it does I have not found a convincing answer for. It seems really fast.